### PR TITLE
Fix attributes list in mufman.raw (also a question in the extended de…

### PR DESCRIPTION
**Pull request by nyanster**
…scription)

Question: does anything convert the .raw files to the .txt files, or is that only for .raw to .html?  Duplicated text/code is never fun!

### CODE REVIEW

**Comment by wyld-sw** [comment]
My understanding is that 'make help' generates both the html and txt files.

**Comment by nyanster** [comment]
I see.  You're right: I've done that and confirmed it is so.  Should the .txt versions be deleted from github then?  Or, how else do you ensure that the .txt versions don't fall behind the .raw versions?

**Comment by digitalcircuit** [comment]
`make help` does not (yet) work on Windows, unfortunately, otherwise we could have the help files always generated at compile time.

It might be worthwhile fixing that first before removing the generated `.txt` files to avoid leaving Windows builds (including automated AppVeyor builds) out of the picture.

**Comment by wyld-sw** [comment]
Thanks, Shane. Good point!

**Pull request merged**
